# If the plugin should auto-update
auto-update: true
on-death:
  # 如果設定為 true, 玩家將會在死亡後隨機遺失一項研究
  reset-random-research: true
  # 在死亡時有機率會重置所有研究. 百分比率 0 至 100.
  # 100 將會始終遺失, 0 將永遠不會遺失
  chance-to-reset-all-researches: 5

on-research:
  # 研究失敗的機率. 百分比率 0 至 100.
  # 100 將始終失敗, 0 將永遠不失敗.
  chance-of-failure: 10

android:
  # 機器人出現故障的機率. 百分比率 0 至 100.
  # 100 將始終故障, 0 將永遠不故障.
  chance-to-malfunction: 10
  # 故障持續時間 (以秒為單位)
  malfunction-duration: 30

messages:
  lost-random-research: '&c你遺忘了隨機的研究!'
  lost-all-research: '&c喔不... 你遺忘了所有的研究!'
  research-failed: '&c研究失敗! 你需要再研究一次 :^)'
  android-malfunctioned: '&c你的機器人出現故障! 讓它冷卻並重新啟動'
